### ISSUE TITLE
Extremely weird behavior of the `MDBDataTable` component 

### ISSUE THREAD

**Issue by zeekhuge** [mdbootstrap/mdb4-react-ui-kit#12]
# Env

```
$ npm --version
7.9.0

```

# Steps To Reproduce: 

Create the base app:
```
$ mkdir test-table && cd test-table
$ create-react-app --template=typescript ./
$ npm i --save mdbreact --legacy-peer-deps
```

Change the `App.tsx` to: 
```
import './App.css';
import {MDBDataTable} from 'mdbreact';

function App() {
    return (
        <MDBDataTable
            data={{
                columns:[{
                    label: 'temp',
                    field: 'key2'
                }],
                rows: [{
                    key1: "value1",
                    key2: "value2",
                    message: "the-message"
                }]
            }}
        />
    );
}

export default App;

```

Start app:
```
$ npm start
```

# Observed Behavior

The table displays "the-message" 

# Expected Behavior

The table should display "value2"

# Questions:

Is there some magic field in `MDBDataTable` called `message` ? Is this just a bug that should have surfaced up by now, but somehow, hasn't ? Or am I just doing something terribly stupid here (lack of sleep and high caffeine maybe) ?

**Comment by krzysiu-w** [comment]
Hi!

Yes, that's a "magic" field in MDBDatatable :smile: When there's no data - it is used to display the no results message from the the`noRecordsFoundLabel` property. That's why it takes precedence before the field declared in the column. So when you are adding the message property - you adding it manually (component generates it when the case above occurs) and it overrides the table data :disappointed:

**Comment by zeekhuge** [comment]
Is this documented somewhere ?

**Comment by krzysiu-w** [comment]
Nope, that's our oversight. We'll add a description to it before the next release (22.11) :)

**Comment by zeekhuge** [comment]
Great. Thanks.
